dataset_path: dataset/database.tsv

folders:
  dataset: {'fasta' : 'dataset/fasta', 'fasta_mut' : 'dataset/fasta_mut', 'pdb_full' : 'dataset/pdb_full'}
  embedding: {'diff': 'embedding/diff', 'wt': 'embedding/wt', 'mut': 'embedding/mut', 'additional_features': 'embedding/additional_features', 'graphs': 'embedding/graphs'}
  splits: {'splits': 'splits_multi'}
  train_val: {'trials': 'trials', 'logs': 'logs', 'results': 'results'}
  contact_map: {'ca': 'ca', 'cb': 'cb'}
  topology: {'topology': 'topology'}
  tda_plots: {'tda_plots': 'tda_plots'}

d3to1: {'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K', 'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
 'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M'}